<a href="https://colab.research.google.com/github/pramaspx/PM-TuRi2-AhmadMiftahHadiPramanaArsjad/blob/main/PM_P4_AhmadMiftahHadiPramanaArsjad_2488010057.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [36]:
import pandas as pd
import numpy as np

# Membuat dataset buatan sendiri
data = {
    'usia': [25, np.nan, 30, 35, np.nan, 40],
    'pendapatan': [5000000, 6000000, np.nan, 8000000, 7500000, np.nan],
    'pendidikan': ['SMA', 'S1', 'S2', 'SMA', 'S1', 'S2'],
    'kota': ['Jakarta', 'Bandung', 'Jakarta', 'Surabaya', 'Bandung', 'Surabaya'],
    'membeli': ['Ya', 'Tidak', 'Ya', 'Tidak', 'Ya', 'Tidak']

}

# Mengubah dictionary menjadi DataFrame
df = pd.DataFrame(data)

# Tampilkan data awal untuk memastikan
print(df)

   usia  pendapatan pendidikan      kota membeli
0  25.0   5000000.0        SMA   Jakarta      Ya
1   NaN   6000000.0         S1   Bandung   Tidak
2  30.0         NaN         S2   Jakarta      Ya
3  35.0   8000000.0        SMA  Surabaya   Tidak
4   NaN   7500000.0         S1   Bandung      Ya
5  40.0         NaN         S2  Surabaya   Tidak

In [43]:
df['usia'] = df['usia'].fillna(df['usia'].median())
df['pendapatan'] = df['pendapatan'].fillna(df['pendapatan'].median())
print(df.isnull().sum(),)
print(df)

usia          0
pendapatan    0
pendidikan    0
kota          0
membeli       0
dtype: int64
   usia  pendapatan pendidikan      kota membeli
0  25.0   5000000.0        SMA   Jakarta      Ya
1  32.5   6000000.0         S1   Bandung   Tidak
2  30.0   6750000.0         S2   Jakarta      Ya
3  35.0   8000000.0        SMA  Surabaya   Tidak
4  32.5   7500000.0         S1   Bandung      Ya
5  40.0   6750000.0         S2  Surabaya   Tidak

In [38]:
X = df.drop(columns=['membeli'])
y = df['membeli']

In [39]:
X['pendidikan'] = X['pendidikan'].map({'SMA':0,'S1':1,'S2':2}) # ordinal
X = pd.get_dummies(X, columns=['kota'], dtype=int) # nominal
y = y.map({'Tidak':0,'Ya':1})

In [40]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(
 X, y, test_size=0.3, random_state=42)

In [41]:
from sklearn.preprocessing import StandardScaler
num = ['usia','pendapatan','pendidikan']
sc = StandardScaler()
X_train[num] = sc.fit_transform(X_train[num])
X_test[num] = sc.transform(X_test[num]) # cegah data leakage

In [42]:
print("--- Verifikasi Akhir (5 Baris Pertama X_train yang Sudah Bersih & Skala Seragam) ---")
print(X_train.head())

--- Verifikasi Akhir (5 Baris Pertama X_train yang Sudah Bersih & Skala Seragam) ---
       usia  pendapatan  pendidikan  kota_Bandung  kota_Jakarta  kota_Surabaya
5  1.521278   -0.942809    0.904534             0             0              1
2 -1.183216   -0.942809    0.904534             0             1              0
4 -0.507093    0.471405   -0.301511             1             0              0
3  0.169031    1.414214   -1.507557             0             0              1

In [44]:
#Latihan 1
df['usia']=[25, np.nan, 30, 35, np.nan, 40]
df['usia'] = df['usia'].fillna(df['usia'].mean())
df

   usia  pendapatan pendidikan      kota membeli
0  25.0   5000000.0        SMA   Jakarta      Ya
1  32.5   6000000.0         S1   Bandung   Tidak
2  30.0   6750000.0         S2   Jakarta      Ya
3  35.0   8000000.0        SMA  Surabaya   Tidak
4  32.5   7500000.0         S1   Bandung      Ya
5  40.0   6750000.0         S2  Surabaya   Tidak

In [46]:
#Latihan 2
from sklearn.preprocessing import StandardScaler,MinMaxScaler
num = ['usia','pendapatan','pendidikan']
sc = MinMaxScaler()
X_train[num] = sc.fit_transform(X_train[num])
X_test[num] = sc.transform(X_test[num])
df.describe()

         usia    pendapatan
count   6.000  6.000000e+00
mean   32.500  6.666667e+06
std     5.000  1.068488e+06
min    25.000  5.000000e+06
25%    30.625  6.187500e+06
50%    32.500  6.750000e+06
75%    34.375  7.312500e+06
max    40.000  8.000000e+06

In [47]:
#latihan 3
df['kota_lahir']=['Jakarta', 'Bandung', 'Jakarta', 'Surabaya', 'Bandung', 'Surabaya']
df_encoded = pd.get_dummies(df, columns=['kota_lahir'],dtype=int)
df_encoded

,usia,pendapatan,pendidikan,kota,membeli,kota_lahir_Bandung,kota_lahir_Jakarta,kota_lahir_Surabaya
0,25.0,5000000.0,SMA,Jakarta,Ya,0,1,0
1,32.5,6000000.0,S1,Bandung,Tidak,1,0,0
2,30.0,6750000.0,S2,Jakarta,Ya,0,1,0
3,35.0,8000000.0,SMA,Surabaya,Tidak,0,0,1
4,32.5,7500000.0,S1,Bandung,Ya,1,0,0
5,40.0,6750000.0,S2,Surabaya,Tidak,0,0,1

Latihan 4
Karena fit_transform digunakan pada data latih untuk mempelajari parameter statistik dan mengubah skalanya, sedangkan transform hanya diterapkan pada data uji menggunakan parameter yang sama persis dari data latih demi mencegah kebocoran data (data leakage).

Refleksi
1. untuk mencegah terjadinya data leakage (kebocoran data). Jika scaling dilakukan sebelum splitting, parameter statistik (seperti rata-rata atau standar deviasi) dari data uji akan ikut dihitung dan tercampur ke dalam data latih. Hal ini akan membuat performa model terlihat sangat bagus saat evaluasi, namun buruk ketika dihadapkan pada data baru di dunia nyata.

2.
- Label Encoding digunakan untuk variabel kategorikal yang bersifat ordinal
- One-Hot Encoding digunakan untuk variabel kategorikal yang bersifat nominal

3. Normalisasi mengubah rentang nilai fitur ke dalam skala tertentu, umumnya berada di antara nilai 0 dan 1. Sedangkan Standardisasi mengubah distribusi data agar memiliki nilai rata-rata (mean) sama dengan 0 dan standar deviasi sama dengan 1 (berpusat pada nol).